ARM64: configs: Set CONFIG_AUDIT=y
Since commit 991bd26e87225058961aeeeb2796624a21aa0749, CONFIG_AUDIT is no longer auto-selected and because it is not defined in defconfig, it remains disabled by default. This config is required for FCM 6, otherwise you will get build errors such as:
ERROR: files are incompatible: Runtime info and framework compatibility matrix are incompatible: No compatible kernel requirement found (kernel FCM version = 6).
For kernel requirements at matrix level 6, Kernel config errors:
    Missing config CONFIG_AUDIT